# Site settings
title: "Franklin Clark"
email: ffffranklin@pobox.com
description: "Franklin Clark shares rants, tips, tricks and secrets on JavaScript and website development."
author: "Franklin Clark"
keywords: "ffffranklin, javascript, frontend, aws, developer, news, web, php, applications"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ffffranklin.com" # the base hostname & protocol for your site
permalink:   /blog/:title/
twitter_username: _ffffranklin
github_username: ffffranklin

# Build settings
markdown: kramdown

exclude:
  - "node_modules"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "bower.json"
  - "package.json"
  - "webpack.config.js"

# Custom variables
assets_url: ''

sass:
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "work"
      type: "pages"
    values:
      layout: "project"
